version: "3.7"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://username:password@db/app
      UPLOAD_PATH: /app/save
      ADMIN_PASSWORD: password
    restart: unless-stopped
    depends_on:
      - db
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend