name: Build And Push

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    name: Build Backend Docker Image
    needs: []
    runs-on: powerful

    permissions:
      packages: write # needed for ghcr.io

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata for Backend Image Build
        id: docker_backend_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/Reman-Hogbisz/hogbisz_cdn_backend
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Docker Build and Push Backend to GHCR
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:Backend"
          push: true
          tags: ${{ steps.docker_backend_meta.outputs.tags }}
          labels: ${{ steps.docker_backend_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
  build-frontend:
    name: Build Frontend Docker Image
    needs: []
    runs-on: powerful

    permissions:
      packages: write # needed for ghcr.io

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata for Frontend Image Build
        id: docker_frontend_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/Reman-Hogbisz/hogbisz_cdn_frontend
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Docker Build and Push Frontend to GHCR
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:Frontend"
          push: true
          tags: ${{ steps.docker_frontend_meta.outputs.tags }}
          labels: ${{ steps.docker_frontend_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
